replicaCount: 2

image:
  repository: abhi3059/fastapi-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Required by some controllers
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Redirect HTTP to HTTPS
  hosts:
    - host: fastapi.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - fastapi.local
      secretName: fastapi-tls

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Non-sensitive environment config for ConfigMap
env:
  CI: ""
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CACHE_TTL: "3600"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: rickmorty
  
# Sensitive data to be mounted from secrets
database:
  userSecretRef: db-secret
  userKey: username
  passwordKey: password

serviceAccount:
  create: true
  name: app-service-account

# -- Prometheus Rule Integration --
prometheus:
  prometheusSpec:
    ruleFiles:
      - /etc/prometheus/alert.rules.yaml
    extraVolumes:
      - name: custom-rules
        configMap:
          name: prometheus-alert-rules
    extraVolumeMounts:
      - name: custom-rules
        mountPath: /etc/prometheus/alert.rules.yaml
        subPath: alert.rules.yaml
        readOnly: true
