apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-pod-kill
  namespace: rickmorty
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - rickmorty
    labelSelectors:
      app: redis
  duration: "30s"
  scheduler:
    cron: "@every 5m"
