apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  username: {{ .Values.database.username | default "postgres" }}
  password: {{ .Values.database.password | default "postgres" }}
