apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  labels:
    app: {{ include "fastapi-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-app.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "fastapi-app.fullname" . }}-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecretRef }}
                  key: {{ .Values.database.userKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecretRef }}
                  key: {{ .Values.database.passwordKey }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: CACHE_TTL
              value: {{ .Values.env.CACHE_TTL | quote }}
            - name: CI
              value: {{ .Values.env.CI | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: fluentd
          image: fluent/fluentd:v1.14-1
          env:
            - name: FLUENTD_ARGS
              value: "--no-supervisor -q"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
