apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring
  labels:
    release: prometheus      
spec:
  selector:
    matchLabels:
      app: fastapi         
  namespaceSelector:
    matchNames:
      - fastapi              
  endpoints:
    - port: http            
      path: /metrics
      interval: 15s
