apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fastapi-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: fastapi-alerts
      rules:
        - alert: HighRequestLatency
          expr: histogram_quantile(0.95, rate(request_latency_seconds_bucket[5m])) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: High latency on API

        - alert: RedisFailuresSpike
          expr: increase(app_redis_failures_total[5m]) > 3
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: Too many Redis failures

        - alert: CrashLoopingPods
          expr: kube_pod_container_status_restarts_total{container="fastapi"} > 3
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: FastAPI container is restarting frequently
